### ISSUE TITLE
Blacklisted didn't work

### ISSUE THREAD

**Issue by NakiriFox** [Test-Account666/LethalCompany-ScannableTools#2]
![QQ_1722881419419](https://github.com/user-attachments/assets/ca901337-5475-47a9-849f-3c3b115e5fba)
![QQ_1722881456124](https://github.com/user-attachments/assets/2b2426f3-df0f-4fc4-a095-a67497e80980)

**Comment by Test-Account666** [comment]
That might have to do with your translation mod. 

I'll have a look if that's fixable

**Comment by NakiriFox** [comment]
thank you :)

**Comment by NakiriFox** [comment]
![QQ_1722913050269](https://github.com/user-attachments/assets/6413099e-d133-4adf-9a1c-6ae7aa48f16a)
It seems that the radar-booster should be included in the default blacklist

**Comment by NakiriFox** [comment]
![QQ_1722913211235](https://github.com/user-attachments/assets/c5b4060a-6d0b-4b7e-9275-7747330ab89a)
![QQ_1722913274152](https://github.com/user-attachments/assets/48451d23-2fc8-44b3-9960-2d79470b17d4)
And all tools without scan node sub text should set an empty scan node sub text.
Such as:
![QQ_1722913398742](https://github.com/user-attachments/assets/5b937846-0cbc-4ae7-a68a-fc1c751f5338)

**Comment by NakiriFox** [comment]
> And all tools without scan node sub text should set an empty scan node sub text.

Perhaps we can create a mod that allows people to customize all added scan node sub texts, so that they can input some interesting text?

example:
    Shovel
    Take it and fight

**Comment by NakiriFox** [comment]
> 这可能与您的翻译模式有关。
> 
> 我会看看是否可以修复

![QQ_1722914021686](https://github.com/user-attachments/assets/441308c9-ef7b-4100-b0a5-92b8612f801e)
Entering the translated text into the blacklist can take effect.
But it's impossible to input every language, a more fundamental solution is needed

**Comment by Test-Account666** [comment]
> > 这可能与您的翻译模式有关。
> > 
> > 我会看看是否可以修复
> 
> ![QQ_1722914021686](https://github.com/user-attachments/assets/441308c9-ef7b-4100-b0a5-92b8612f801e)
> Entering the translated text into the blacklist can take effect.
> But it's impossible to input every language, a more fundamental solution is needed

Your translation mod modifies the name inside the Item Properties.

I don't see a way to fix that

**Comment by Test-Account666** [comment]
> ![QQ_1722913211235](https://github.com/user-attachments/assets/c5b4060a-6d0b-4b7e-9275-7747330ab89a)
> ![QQ_1722913274152](https://github.com/user-attachments/assets/48451d23-2fc8-44b3-9960-2d79470b17d4)
> And all tools without scan node sub text should set an empty scan node sub text.
> Such as:
> ![QQ_1722913398742](https://github.com/user-attachments/assets/5b937846-0cbc-4ae7-a68a-fc1c751f5338)
> 

I'm guessing that your translation mod needs an overhaul. 

Since that text is set after the initial is empty check.

Otherwise it wouldn't leave floating text

**Comment by NakiriFox** [comment]
I'm trying to fix it
